# Generated by Django 4.2.4 on 2023-12-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_phone',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
